### PR TITLE
Remove empty lines from html

### PR DESCRIPTION
**Pull request by benoittgt**
Rdoc/Erb generate a lot of extra empty lines. After a discussion https://github.com/rspec/rspec.github.io/pull/136#pullrequestreview-384210734 and few try in RDoc and Erb the easiest solution at the moment is to remove line by ourself.

Dependent of https://github.com/rspec/rspec.github.io/pull/138

### CODE REVIEW

**Comment by pirj** [comment]
```
−646,764 
```
image

👍 

How do you remove it, did you update `rspec-dev` scripts?

**Comment by pirj** [comment]
Is this only needed for 2.14 and 2.99?

**Comment by JonRowe** [comment]
So this is mostly new line removals (I had to diff manually and grep) but also adds some div closing tags and I'm not sure why.

**Comment by benoittgt** [comment]
Sorry for the big commit. Feel free to make any remarks of my work. I am also here to constantly improve myself. Advices and suggestions are always welcome. 😊

It should have added commands to show additions and deletions in PR body.

Here is the diff without empty lines and "Generated on..." timestamp
```sh
$ git diff -U0 HEAD\~1..HEAD | \
  grep -v '^@@ ' | \
  grep -v '^-[[:blank:]]*$' | \
  grep -B1 -E '^(-[^-]|\+[^+])[^  Generated on Sun]'
```

```diff
+++ b/source/documentation/3.0/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.1/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.2/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.2/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.3/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.3/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.4/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.4/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.5/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.5/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.6/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.6/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.7/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.7/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.8/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.8/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.9/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.9/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
```

So div are only moved.

**Comment by benoittgt** [comment]
> Is this only needed for 2.14 and 2.99?
It is needed for every version.

**Comment by JonRowe** [comment]
Oh its removing some spacing after the tags? Thats ok then.

**Comment by benoittgt** [comment]
Yep @JonRowe :)

Capture d’écran 2020-04-07 à 17 18 39

**Comment by JonRowe** [comment]
I'd suggest not merging until #138 is merged, then merge this into source, because it makes diffing 138 way more difficult.

**Comment by benoittgt** [comment]
No problem Jon

**Comment by benoittgt** [comment]
The last change remove only blank lines:
```sh
$ git diff -U0 HEAD\~1..HEAD | \                                                                           
  grep -v '^@@ ' | \
  grep -v '^-[[:blank:]]*$' | \
  grep -B1 -E '^(-[^-]|\+[^+])[^  Generated on]'
```

```diff
+++ b/source/documentation/3.0/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.1/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.2/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.2/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.3/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.3/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.4/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.4/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.5/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.5/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.6/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.6/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.7/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.7/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.8/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.8/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
--
+++ b/source/documentation/3.9/rspec-core/RSpec/Core/Notifications/ExamplesNotification.html
-</div>
+</div>
--
+++ b/source/documentation/3.9/rspec-core/RSpec/Core/Runner.html
-</div>
+</div>
```

**Pull request merged**
