### PR TITLE
Remove push by hand instructions for staging.

### PR DESCRIPTION
**Pull request by JonRowe**
@pirj I'm removing the push by hand instructions for staging, you need to remove the `CNAME` file for this to happen and I'd rather not risk it.

### CODE REVIEW

**Comment by pirj** [comment]
I'd rather remove `CNAME` from the repo.

It seems to be only needed to set up subdomains that we have no use of:

> To set up a www or custom subdomain, such as www.example.com or blog.example.com, you must create a CNAME file in your site's repository and configure a CNAME record with your DNS provider.

> This will create a commit that adds a CNAME file in the root of your publishing source.

**Comment by JonRowe** [comment]
It has always been required in the past, I think the docs are misleading, note that after saying `custom subdomain` they then say `such as www.example.com` which is not a custom subdomain at all, its the default for most web browsers.

As an aside, when quoting docs, can you link back to the source.

**Comment by pirj** [comment]
Sure, it's [here](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain) and [here](https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages). Specifically:
> GitHub Pages works with two types of domains: subdomains and apex domains. 
> www subdomain | www.example.com
> Apex domain | example.com

[Apex domains-specific GH pages doc](https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages#using-an-apex-domain-for-your-github-pages-site).

I can't find anyone referring to `www` as a "subdomain" directly and do their best at avoiding this term.
[Heroku is brave enough to list `www` as a "subdomain" in their glossary](https://devcenter.heroku.com/articles/custom-domains#domain-name-glossary). [Github follows this](https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages).

I believe in any case, it's best to double-check with Github support if we can safely remove `CNAME` for apex domains and rely on the "Custom domain" setting exclusively. Or what is their solution to host the same site on two different domains using a single repository.

**Comment by JonRowe** [comment]
> # Configuring an apex domain
> To set up an apex domain, such as example.com, you must configure a CNAME file in your GitHub Pages repository and an ALIAS, ANAME, or A record with your DNS provider.

From: https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by pirj** [comment]
That's quite sad.

Relying on Github for properly resolving which should be served at rspec.info seems to be the only an option.
It will work provided a guarantee that if "Custom domain" option in the repository is **not** set, Github won't make an attempt to serve this repository by that DNS name even if CNAME is part of the repo.
Do you want me to check with Github support about that?

**Pull request merged**
