### PR TITLE
Bradley is back from time off so let’s move him back to current team.

### PR DESCRIPTION
**Pull request by myronmarston**
I can't get this to render right, though:

screen shot 2015-10-02 at 6 43 19 am

Anyone with more CSS know-how than I have want to take a stab at fixing it?

/cc @rspec/rspec

### CODE REVIEW

**Comment by soulcutter** [comment]
That should fix the padding.

**Comment by soulcutter** [comment]
I merged, but I cannot deploy the changes.

**Comment by myronmarston** [comment]
Thanks!  I can't deploy, either...I get:

```
...
There were errors during this build, re-run with `middleman build --verbose` to see the full exception.
```

@JonRowe, can you take a look?

**Comment by soulcutter** [comment]
Odd, it built for me, although I got several bourbon sass warnings

Bradley Schaefer

**Comment by JonRowe** [comment]
Deployed

**Comment by JonRowe** [comment]
It builds fine for me so it might be a gem version issue?

**Comment by JonRowe** [comment]
My gems for comparison https://gist.github.com/JonRowe/4a9bffd7e0bcbfa920ab

**Comment by myronmarston** [comment]
Somehow the deploy got borked, @JonRowe.  Notice the lack of styles at http://rspec.info/documentation/3.3/rspec-core/.

Want to try re-deploying?  I tried but I'm still getting the error message.

**Comment by JonRowe** [comment]
Working on it

**Comment by JonRowe** [comment]
I'm not sure when this was last working, previous commits on master seem to have the same issue, the fix I worked up before doesn't seem to be the one we used in the end (as the plugin hasn't been used to generate the doc files so the css is in the wrong place) I have a solution involving using middleman's proxy directive but at the moment it causes my middleman build to fail for the "latest" files

**Comment by myronmarston** [comment]
Previously we had seen it fail on some deploys but then work on a redeploy.  Is that no longer the case?

**Comment by JonRowe** [comment]
Doesn't seem to be

**Comment by JonRowe** [comment]
Any idea how we fixed this in the end? I can't find evidence of anything but the plugin I wrote, but that doesn't seem to have been used...

**Comment by myronmarston** [comment]
Nope, sorry.

**Pull request merged**
