### PR TITLE
Fix document css

### PR DESCRIPTION
**Pull request by JonRowe**
This repairs the styles for the documentation, and I've tested it looks ok on staging.

### CODE REVIEW

**Comment by JonRowe** [comment]
FWIW I did this with sed rather than regenerating the docs, a more permanent solution is to do this with a rake task unless I can somehow configure a "before build" step in middleman.

**Comment by myronmarston** [comment]
LGTM.  Can you take a stab at fixing our [doc generation rake task](https://github.com/rspec/rspec-dev/blob/3a2bba6f8c1dcb116958da07b839187022b727d0/Rakefile#L62-L70) so that we don't have to manually fix this in the future?

Ideally that would be in place before 3.4 is released so when we build the docs for 3.4 it just works.

**Comment by JonRowe** [comment]
Will do, I didn't realise we'd setup a rake task already :)

**Pull request merged**
