### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by JonRowe**
I found more to do here, sorry. /cc @myronmarston

### CODE REVIEW

**Comment by myronmarston** [comment]
Github is telling me:

> Sorry, we could not display the entire diff because too many files (1,122) changed.

...so I didn't view the whole thing, but what I saw looked fine.  I trust you, so merge away.

**Comment by JonRowe** [comment]
It's basically all the nested html files had ../../ paths so my `ag | sed` failed first time around and I didn't notice until I checked the other files.

**Comment by myronmarston** [comment]
Something in either this or #76 broke things.  When you click on "Class List" or "Method List" it used to provide a navigable drop-down and also allow you to type in the search box to filter.  For 3.2 and before that seems to work:

http://rspec.info/documentation/3.2/rspec-expectations/

But for 3.3, the "Class List" and "Method List" links just link to a page that display the list (presumably, YARD's fallback when the js doesn't work) and the search box does not work:

http://rspec.info/documentation/3.3/rspec-expectations/

Note that the 3.3 docs for rspec-core and rspec-rails seem to work here.  It's just rspec-mocks and rspec-expectations that have this problem.

Can you take a look, @JonRowe?  Would be nice to have this fixed when it comes time to generate the 3.4 docs this week.

**Comment by JonRowe** [comment]
It's the same problem as the css, so the solution for that could be modified to do this, I'm not sure I'll have time to get to it this week but I'll try.

**Pull request merged**
