### PR TITLE
Added link to screencast below book.

### PR DESCRIPTION
**Pull request by xaviershay**
screen shot 2016-01-13 at 5 24 23 pm

@myronmarston

### CODE REVIEW

**Comment by JonRowe** [comment]
Do you need a hand deploying this?

**Comment by xaviershay** [comment]
presumably I could read some docs or something, but I've never done so hand would be appreciated :)

**Comment by JonRowe** [comment]
It should be as simple as `middleman deploy` (for staging) and `TARGET=prod middleman deploy` (for http://rspec.info/) but I know some people have issues with the site not building properly, it's also good to check something hasn't malfunctioned and broken the docs on staging before pushing to the main site

**Comment by xaviershay** [comment]
```
ERROR: Permission to RSpec-Staging/rspec-staging.github.io.git denied to xaviershay.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Permissions please :)

**Comment by JonRowe** [comment]
Done! Sorry!

**Comment by xaviershay** [comment]
hrmmm, I saw the "you have been added" email come through but still same permission denied message. Did you actually make me a committer, or just add to org?

(or could you just deploy it for me?)

**Comment by JonRowe** [comment]
Deployed

**Comment by JonRowe** [comment]
You hadn't accepted the invitation to the team, which is why you still don't have permissions :/

**Comment by xaviershay** [comment]
I am such an idiot. Thanks for the deploy.

**Pull request merged**
