### PR TITLE
Edits for the certificate blog post

### PR DESCRIPTION
**Pull request by samphippen**

### CODE REVIEW

**Comment by myronmarston** [comment]
Well that was fast! I guess by "today" you meant "in the next couple minutes", eh?

**Comment by samphippen** [comment]
:3

**Comment by myronmarston** [comment]
Works for me.  You mind renaming the file so the date is `2015-01-30`?  I'll plan to publish this tomorrow (which I guess will still be today in your timezone).

**Comment by myronmarston** [comment]
Thanks, @samphippen.  I'll deploy this shortly.

**Comment by myronmarston** [comment]
Deployed.

**Pull request merged**
