### PR TITLE
Add 3-10 docs

### PR DESCRIPTION
**Pull request by JonRowe**
First pass at docs on our site for 3.10 (yes they've been missing all this time 😬) the menu is slightly out of wack but at least they're available. (Previews on https://rspec-staging.github.io/documentation/3.10/rspec-core/ etc)

### CODE REVIEW

**Review by pirj — APPROVED** [review]
Couldn't spot any difference. Apart from the `Generated on` footer - it's now visible 👍

**Comment by JonRowe** [comment]
3.10 was not visible previously, its on staging now ;)

**Comment by pirj** [comment]
Yes, it's clear. I've been comparing https://rspec-staging.github.io/documentation/3.10/rspec-core/ to https://rspec.info/documentation/3.9/rspec-core/

**Comment by JonRowe** [comment]
(Fixed the menu and verified against staging)

**Pull request merged**
