### PR TITLE
Use redcarpet as a Markdown renderer instead of kramdown

### PR DESCRIPTION
**Pull request by yujinakayama**
for more compatibility with GitHub flavored Markdown.

This should fix https://github.com/rspec/rspec.github.io/pull/92#issuecomment-180912560.

### CODE REVIEW

**Comment by myronmarston** [comment]
Does changing require us to change all the code blocks in all markdown files?

**Comment by JonRowe** [comment]
It shouldn't do? Github flavoured markdown is a superset of normal markdown, but it would be good to check.

**Comment by myronmarston** [comment]
As I understand it, standard markdown does not support fenced code blocks. Some extensions like kramdown chose triple tilde for them whereas GFM chose triple back tick.

**Comment by yujinakayama** [comment]
redcarpet supports triple tilde also for fenced code blocks. However, I noticed that redcarpet does not generate named anchors for header, so I close this PR for now.

```diff
-<h2 id="rspec-20">RSpec 2.0</h2>
+<h2>RSpec 2.0</h2>
```

**Pull request closed without merging**
