### PR TITLE
Dropdown menu on hover for doc link versions.

### PR DESCRIPTION
**Pull request by brenfrow**
This change provides a small menu (of doc links) that opens on hover, as opposed to a horizontal list.

NOW:
image
BEFORE:
image

### CODE REVIEW

**Comment by JonRowe** [comment]
Some explanations of the changes would be nice :) Also I like to attach screenshots when working with css/js changes (or gifs) to ease the review process...

**Comment by mootpointer** [comment]
Yeah. The header hierarchy on the blog needs to get fixed up.

**Comment by JonRowe** [comment]
Much reply, wrong issue, such doge.

**Comment by mootpointer** [comment]
Very much so. Apologies.

**Comment by myronmarston** [comment]
@JonRowe -- @brenfrow is a coworker/friend of mine who I asked to work on this.  I just hadn't got around to reviewing it yet...

**Comment by brenfrow** [comment]
Explanation and pictures included!

**Comment by JonRowe** [comment]
I think I favour actually listing all of the versions on this page, rather than hiding them in a dropdown, but having some sort of dropdown nav bar for when actually in the docs...

**Comment by myronmarston** [comment]
I specifically asked @brenfrow to do this since I was unhappy with the horizontal list we had before.  I think this is much better.  Thanks, @brenfrow.  We can always iterate from here, @JonRowe, based on your ideas.

**Comment by myronmarston** [comment]
I deployed this to rspec.github.io.  It looks great...however, now the doc pages are messed up.  @JonRowe what did we do before to fix them?

**Comment by myronmarston** [comment]
Also, @JonRowe, is there a way to rollback?  It'd be good to know how to do that (maybe we can put it in the README?) so that when there's a botched deploy I can undo it.

**Comment by brenfrow** [comment]
the docs are linking to `http://rspec.github.io/documentation/3.1/rspec-core/js/jquery.js`
when they need to link to http://rspec.github.io/javascripts/docs/jquery.js

**Comment by brenfrow** [comment]
Can you do something in the docs like I tried to do here: https://github.com/brenfrow/rspec.github.io/commit/9a678588159ac9b842fde1ae7e10e7ca923f4968

**Comment by JonRowe** [comment]
> Also, @JonRowe, is there a way to rollback?

You'd have to revert the merge and redeploy...

> I deployed this to rspec.github.io. It looks great...however, now the doc pages are messed up. @JonRowe what did we do before to fix them?

Nothing, I just redepoyed it and it's fine again...

**Comment by JonRowe** [comment]
You are deploying with `middleman deploy` right?

**Comment by myronmarston** [comment]
Yep.  Here's what I did:

```
➜  rspec.github.io git:(source) be middleman deploy
== LiveReload accepting connections from http://10.0.1.2:4567 (localhost)
         run  middleman build from "."
      create  build/stylesheets/application.css
      create  build/stylesheets/docs/common.css
      create  build/stylesheets/docs/full_list.css
      create  build/stylesheets/docs/style.css
      create  build/stylesheets/normalize.css
      create  build/stylesheets/pages/about.css
      create  build/stylesheets/pages/blog.css
      create  build/stylesheets/pages/contributing.css
      create  build/stylesheets/pages/documentation.css
      create  build/stylesheets/pages/help.css
      create  build/stylesheets/pages/index.css
      create  build/stylesheets/pages/upgrading-from-rspec-2.css
      create  build/images/aaron_k.png
      create  build/images/andy_l.png
      create  build/images/aslak_h.png
      create  build/images/background.png
      create  build/images/bradley_s.png
      create  build/images/brian_t.png
      create  build/images/brutus-half.png
      create  build/images/brutus.png
      create  build/images/chad_h.png
      create  build/images/dave_a.png
      create  build/images/david_c.png
      create  build/images/github-icon.png
      create  build/images/jon_r.png
      create  build/images/justin_k.png
      create  build/images/link.png
      create  build/images/logo-small.png
      create  build/images/logo.png
      create  build/images/yuji_n.png
      create  build/images/xavier_s.png
      create  build/images/twitter-icon.png
      create  build/images/steven_b.png
      create  build/images/stackoverflow-icon.png
      create  build/images/luke_r.png
      create  build/images/rspec_book.png
      create  build/images/pat_m.png
      create  build/images/myron_m.png
      create  build/images/middleman.png
      create  build/images/sam_p.png
      create  build/javascripts/all.js
      create  build/javascripts/docs/app.js
      create  build/javascripts/docs/full_list.js
      create  build/javascripts/docs/jquery.js
      create  build/documentation/3.2/rspec-expectations/RSpec/Matchers/BuiltIn/YieldSuccessiveArgs.html
      [truncated]
      create  /Users/myron/code/rspec-dev/repos/rspec.github.io/build/mstile-310x310.png
== LiveReload accepting connections from http://10.0.1.2:4567 (localhost)
== LiveReload accepting connections from http://10.0.1.2:4567 (localhost)
## Deploying via git to remote="origin" and branch="master"
== LiveReload accepting connections from http://10.0.1.2:4567 (localhost)
Counting objects: 1167, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1092/1092), done.
Writing objects: 100% (1167/1167), 2.47 MiB | 946 KiB/s, done.
Total 1167 (delta 846), reused 0 (delta 0)
To git@github.com:rspec/rspec.github.io.git
 + b493e6c...cc692d5 master -> master (forced update)
```

I noticed that `master` doesn't have my deploy commit though...did you force push over it?

BTW, I'm finding it annoying that the main branch we work off of is `source` instead of `master`.  Among other things, I have tooling that assumes that `master` is the main branch.  Does github pages reserve master for the deployed content?  Or can we some how get `master` to be the main branch?

**Comment by myronmarston** [comment]
BTW, @JonRowe, at this point, the site is at a point I'm happy with and I'd like to update rspec.info DNS.  Before doing that, though, I want to be sure I can safely deploy so that I can publish the blog posts that are in the pipeline.  Maybe we can pair to figure out what the problem is?

Another thing that would help is a staging environment....how hard would it be to have rspec-staging.github.io be our staging site we can push to test things out?

**Comment by JonRowe** [comment]
> BTW, I'm finding it annoying that the main branch we work off of is source instead of master. Among other things, I have tooling that assumes that master is the main branch. Does github pages reserve master for the deployed content?

For it to work off the apex `rspec.github.io` `master` is reserved for content

> Or can we some how get master to be the main branch?

Not really, we could change this to being a normal repo and have a `gh-pages` branch but then the url would be `rspec.github.io/repo-name` again which I think is undesirable and makes it harder to `ALIAS`/`CNAME` `rspec.info` to it.

> I noticed that master doesn't have my deploy commit though...did you force push over it?

Pass,  I'm not sure what `middleman deploy` does, note you're not supposed to manipulate `master` manually using our deploy strategy...

> Another thing that would help is a staging environment....how hard would it be to have rspec-staging.github.io be our staging site we can push to test things out?

Needs another organisation and repo but otherwise not that hard see http://rspec-staging.github.io/ note that due to our need for it to be an apex domain, and how the github pages naming system works the separate organisation and repo are necessary.

**Comment by myronmarston** [comment]
Thanks.  I'll play with deploying to rspec-staging and see if I can get that to work.

**Comment by JonRowe** [comment]
I'm just tweaking the config to make it easier, a manual push seemed to have the same issue with docs as before

**Comment by JonRowe** [comment]
Worked with my middleman deploy :/

**Pull request merged**
