### PR TITLE
Update doc with updated yard 

### PR DESCRIPTION
**Pull request by benoittgt**
`bundle exec rake "update_docs[3.9, enable-yard-and-bump-doc]"` from `rspec-dev`

Yard update goes from https://github.com/lsegal/yard/compare/v0.9.12...v0.9.24

## To do

- [x] Fix markdown formating of command line arguments https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579821529
- [x] Fix README formating in rspec-rails. https://github.com/rspec/rspec-dev/pull/237
- [x] Use proper README for all generated doc. https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579790316
- [x] Avoid useless carriage return after method definition https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579831421. See https://github.com/lsegal/yard/issues/1313. ⚠**Stick to Ruby 2.6.3 for the moment.**⚠
- [x] Keep all comments even if they are before module definition https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579835118 
  - This not the proper behavior to keep the comment. The new behavior is the one that is expected when you read the code.
- [x] https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579853748 
  - Add a blank line as suggested in comments

--------
## Index

There is a change in https://github.com/lsegal/yard/releases/tag/v0.9.19
> Fixed parsing order of README files. YARD will now prefer README over
> README.md over README.x.md or README-x.md (and the like). READMEs will now
> also be ordered by filename; the first README is still chosen unless
> --readme is provided.

This the page you get when you on the version number in documentation -> http://rspec.info/documentation/

At the moment we jump to https://github.com/rspec/rspec-rails/blob/master/README_DEV.md

Do we want to keep this behavior? With the last yard version we have 

Capture d’écran 2020-01-02 à 14 32 44

Do we want to change the index page? `README_DEV.md` seems pretty old but maybe we can update it.

## Doc version

~~This current version draft is incorrect because the branch used in each repo is `update-travis-build-scripts-2020-01-01-for-master`. And `update-travis-build-scripts-2020-01-01-for-master` start from master not last release/maintenance branch.~~

~~So I think the yard update should go on maintenance branch?~~
Done:
- https://github.com/rspec/rspec-core/pull/2683
- https://github.com/rspec/rspec-expectations/pull/1152
- https://github.com/rspec/rspec-mocks/pull/1311
- https://github.com/rspec/rspec-rails/compare/3-9-maintenance...enable-yard-and-bump-doc?expand=1 not a new PR yet, because this is similar to https://github.com/rspec/rspec-rails/pull/1938

---

Also the documentation rake task [has been build](https://github.com/rspec/rspec-dev/pull/109) to work on many repo at the same time. Soon `rspec-rails` will be released to 4. Should we split rake task for `rspec-rails`, then `rspec-mocks`, `rspec-core`, `rspec-expectations`?
At the moment this lead to rspec-rails doc published as 3.9 with beta features like ActionCable testing.

### CODE REVIEW

**Comment by benoittgt** [comment]
I checked many pagse and didn't find any visual regression.

**Comment by benoittgt** [comment]
Initial PR has been updated with new rake command. The doc is now generated using 3-9-maintenance branchs + yard update.

**Comment by JonRowe** [comment]
@benoittgt We have the staging site so if you're confident your PRs are ok we should add them here, merge and deploy to staging, then maybe run `https://percy.io/visual-testing` on them to check for changes on any pages against master?

**Comment by benoittgt** [comment]
Percy is a good idea. I looked at it. I think it will require a little bit of setup. Their is a lot of visual changes with the _frame_ (left menu) and various CSS adjustments. I would love to have a clear output from Percy. Not too polluted by the left menu frame. I will give a better try tomorrow.

At the moment I have something that not really help us 😅:

Capture d’écran 2020-01-05 à 18 25 17

**Comment by benoittgt** [comment]
Ok I tried https://github.com/evolvingweb/sitediff and https://code.google.com/archive/p/daisydiff/ but their too many noise in diff.

What can I do is a visual review of each page side by side. If you think it's ok @JonRowe tell me.

Also if you can tell me what you want to do [with](https://github.com/rspec/rspec.github.io/pull/131#issue-358651556):
> Do we want to change the index page? README_DEV.md seems pretty old but maybe we can update it.

**Comment by benoittgt** [comment]
I will try to do it before this week-end to close all related PR.

**Comment by JonRowe** [comment]
Personally I think the solution is to write a script with nokogiri to pull out the text and diff it that way, we don't care about HTML changes just content changes.

I also don't want to change the index readme

**Comment by benoittgt** [comment]
Hello

I worked on very basic script that will generate a text diff between two version of the yard documentation.

https://github.com/benoittgt/sitediff_rspec

The script [removes part of the documentation](https://github.com/benoittgt/sitediff_rspec/blob/master/nokorigi-diff.rb#L11-L18) to avoid some noise.

For example:
- `Assertions` moved:
Capture d’écran 2020-01-16 à 15 28 08
- File list
Capture d’écran 2020-01-16 à 20 30 00
- Summary signatures ("object" is in a different position). I still need to improve this noisy change.
Capture d’écran 2020-01-16 à 20 31 36

I also disable all `"collapse"`, they change from `(collapse)` to `{collapse}`. We still ends up with a diff with some work:
- `git diff` without `--word-diff` option https://github.com/benoittgt/sitediff_rspec/blob/master/export/rspec-rails-RSpec-Rails_no_word.diff
- `git diff` with `--word-diff` option. I use this setting to better visualize long line diff. https://github.com/benoittgt/sitediff_rspec/blob/master/export/rspec-rails-RSpec-Rails.diff

I only worked on one page at the moment. So their is probably more surprise in other pages. I am wondering. How much we want to customize the script to get as low as possible of differences. It will needs special rules for each of differences. 

I stop it to ask for a first feedback before going further. Thanks 😊

**Comment by JonRowe** [comment]
I love this approach @benoittgt

**Comment by benoittgt** [comment]
Sorry @JonRowe. Their is "big" change in yard doc. "method summary" are moved at the end of the documentation. You have to click on it. 

Left updated yard            |         Right current yard

Capture d’écran 2020-01-24 à 15 12 03

At the end of doc you can get details.

Capture d’écran 2020-01-24 à 15 12 18

**Comment by benoittgt** [comment]
I will switch the script to check all the page of current yard and will inspect diff. 😱

**Comment by JonRowe** [comment]
Are you sure they're just not collapsed?
Screen Shot 2020-01-24 at 20 01 17

**Comment by JonRowe** [comment]
No need to apologise, thank you for looking at this!

**Comment by benoittgt** [comment]
> I love this approach @benoittgt great work, theres some bits wrong in some of the diffs:
> 
> ```diff
>  defdef selfself..add_test_type_configurationsadd_test_type_configurations((configconfig))
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::ControllerExampleGroupControllerExampleGroup,, :type:type =>=> :controller:controller
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::HelperExampleGroupHelperExampleGroup,,     :type:type =>=> :helper:helper
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::ModelExampleGroupModelExampleGroup,,      :type:type =>=> :model:model
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::RequestExampleGroupRequestExampleGroup,,    :type:type =>=> :request:request
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::RoutingExampleGroupRoutingExampleGroup,,    :type:type =>=> :routing:routing
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::ViewExampleGroupViewExampleGroup,,       :type:type =>=> :view:view
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::FeatureExampleGroupFeatureExampleGroup,,    :type:type =>=> :feature:feature
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::MatchersMatchers
> -  configconfig..includeinclude RSpecRSpec::::RailsRails::::SystemExampleGroupSystemExampleGroup,, :type:type =>=> :system:system
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::ControllerExampleGroupControllerExampleGroupControllerExampleGroupControllerExampleGroup,, :type:type =>=> :controller:controller
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::HelperExampleGroupHelperExampleGroupHelperExampleGroupHelperExampleGroup,,     :type:type =>=> :helper:helper
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::ModelExampleGroupModelExampleGroupModelExampleGroupModelExampleGroup,,      :type:type =>=> :model:model
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::RequestExampleGroupRequestExampleGroupRequestExampleGroupRequestExampleGroup,,    :type:type =>=> :request:request
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::RoutingExampleGroupRoutingExampleGroupRoutingExampleGroupRoutingExampleGroup,,    :type:type =>=> :routing:routing
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::ViewExampleGroupViewExampleGroupViewExampleGroupViewExampleGroup,,       :type:type =>=> :view:view
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::FeatureExampleGroupFeatureExampleGroupFeatureExampleGroupFeatureExampleGroup,,    :type:type =>=> :feature:feature
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::MatchersMatchersMatchersMatchers
> +  configconfig..includeinclude RSpecRSpecRSpecRSpec::::RailsRailsRailsRails::::SystemExampleGroupSystemExampleGroupSystemExampleGroupSystemExampleGroup,, :type:type =>=> :system:system
>  endend# File 'lib/rspec/rails/configuration.rb', line 43
> ```

So for this. In the current website, object class are links and in the new website we do not have the link again. I am using [`traverse`](https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Node#traverse-instance_method) from Nokogiri to go threw all children but in that case it means I will check the old website node for `RSpec` multiple times (`"const"` class, `"object_link"` sub class, `"a"` link, text content).

Current website:
```html
<span class="const"> <!-- node.test -> "Rspec" -->
  <span class="object_link"> <!-- node.test -> "Rspec" -->
    <a href="../RSpec.html" title="RSpec (module)">RSpec</a> <!-- node.test -> "Rspec" -->
  </span>
</span>
```

Last yard:
```html
<span class="const">RSpec</span>
```
2 `"RSpec" will be added to text output.

I have changed a lot the script to make the diff. I will publish my findings today. I will handle this special case too.

**Comment by benoittgt** [comment]
Ok

So I had to remove few things to get not too noisy diff. https://github.com/benoittgt/sitediff_rspec/blob/master/README.md#elements-in-yard-doc-altered
I made a [hacky script](https://github.com/benoittgt/sitediff_rspec/blob/master/nokorigi-diff.rb) for that.

The full diff is here: https://github.com/benoittgt/sitediff_rspec/blob/master/README.md#output

There is still some wrong diff that produce unrealevant noise. I will dig into that diff tomorrow and tell you if I see something that should be discussed.

To do:
- [ ] Change yard command to do not alter index link

**Comment by benoittgt** [comment]
The index doc in yard doc was README.md in all rspec repos expect rspec-rails where is was README-DEV.md. I think we should switch to README.md to all repos.

**Comment by JonRowe** [comment]
I agree

**Comment by benoittgt** [comment]
There is something weird from yard.
We have [this code](https://github.com/rspec/rspec-core/blob/36fa69aaba90278e68c75da92101630856ef47e9/lib/rspec/core/configuration.rb#L29)
```ruby
#... separate custom file using the --options command-line parameter.
```

Capture d’écran 2020-01-29 à 16 40 58

Yard display `–options` instead of `--options`

**Comment by benoittgt** [comment]
Also with [the code](https://github.com/rspec/rspec-core/blob/3-9-maintenance/lib/rspec/core/configuration.rb#L1024):

```ruby
      def reporter
	        # @reporter_buffer should only ever be set in this method to cover
	        # initialization of @reporter.
```

Capture d’écran 2020-01-29 à 17 05 56

First comment line have carriage return removed.

**Comment by benoittgt** [comment]
There is a big remove [of the comment from](https://github.com/rspec/rspec-core/blob/enable-yard-and-bump-doc/lib/rspec/core/formatters.rb#L2-L67) `RSpec::Core::Formatters`

Capture d’écran 2020-01-29 à 17 16 12

**Comment by benoittgt** [comment]
Again "Overview" rely on a different part.

Code : https://github.com/rspec/rspec-rails/blob/a60adc94694177ca8cf3d126f6684c579e83307e/lib/rspec/rails/example/mailer_example_group.rb#L1-L16

Capture d’écran 2020-01-29 à 17 54 10

**Comment by benoittgt** [comment]
@lsegal by any chance do you have ideas for the last 4 comments?

Thanks

**Comment by benoittgt** [comment]
For https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579821529 and the weird `--X` formatting. RedCarpet was not properly installed in repos. I did a `bundle exec rake run["bundle update redcarpet"]` from `rspec-dev` and it fix the issue. 

Capture d’écran 2020-02-26 à 15 33 19

BTW. I will keep a to do list on the initial PR body. To follow the remaining tasks.

**Comment by MSP-Greg** [comment]
@benoittgt

Saw your issue in YARD, and ended up here.  The problem above with `RSpec::Core::Formatters` can be solved by adding a blank line below the first line:
```
RSpec::Support.require_rspec_support "directory_maker"
```

I think it's a little different than the YARD issue, as the above code line isn't parsed by YARD.

JFYI, for a long time, everything was stable.  Then RDoc switched from using their own Ruby parser to Ripper, and small changes have been made to Ripper (which really didn't care about comments) that have resulted in small breakages to YARD based doc systems...

**Comment by benoittgt** [comment]
Thank you very much @MSP-Greg. I tried to add one line on `RSpec::Support.require_rspec_support "directory_maker"`

```diff
--- a/lib/rspec/core/formatters.rb
+++ b/lib/rspec/core/formatters.rb
@@ -1,3 +1,4 @@
+
 RSpec::Support.require_rspec_support "directory_maker"
```

But I am trying to fix this for example this part:
http://rspec.info/documentation/3.9/rspec-core/RSpec/Core/Configuration.html#reporter-instance_method

How is different. I am gonna look at Ripper.

**Comment by MSP-Greg** [comment]
@benoittgt 

Just to be clear, the added line in formatters.rb needs to go between the first code line and the comments that are after it.

Re the problem with the `RSpec::Core::Configuration#reporter`, I'm not seeing that with YARD 0.9.20, at least not at https://msp-greg.github.io/rspec/RSpec/Core/Configuration.html#reporter-instance_method.

But, I've got a lot patches to try to allow parsing RDoc style comments for Ruby docs, etc.  I'm also using CommonMarker, but that shouldn't affect the code block issue...

**Comment by benoittgt** [comment]
Thanks I'm gonna take a look. In the meantime I remove the most code I could to have a very basic reproduction case https://github.com/benoittgt/rspec-core/tree/only-configuration-reporter

Thanks a lot for your help @MSP-Greg. Very appreciated

**Comment by benoittgt** [comment]
Their is probably an issue with Ripper since Ruby 2.7. https://redmine.ruby-lang.org/issues/16675

I will probably generate the documentation using 2.6.3 in the meantime to avoid all those changes in source block of documentation, or choose a different Ruby parser in Yard. 

@JonRowe Your idea to compare version using a tools was a good suggestion. 😄

**Comment by benoittgt** [comment]
This is not an issue with Ripper. There is a change in Ruby 2.7

> Comment lines can be placed between fluent dot now. _(source)[https://sourcediving.com/ruby-2-7-news-commentary-by-cookpads-full-time-ruby-comitters-bdbaacb36d0c]_

```ruby
foo
  # .bar
  .baz #=> foo.baz
```

That's why we have this kind of surprise. I will finish this first then probably try to look at yard if something can be done 🤷‍♂

**Comment by benoittgt** [comment]
Thanks @MSP-Greg. You were right, adding blank line fix https://github.com/rspec/rspec.github.io/pull/131#issuecomment-579835118

**Comment by benoittgt** [comment]
We are pretty ok. Some remaining noise in the [diff](https://github.com/benoittgt/sitediff_rspec#output) but I inspect most of them without noticing any visual regressions.

There is a change in `documentation/3.9/rspec-core/RSpec/Core/Formatters.html` because I added a blank line to avoid hiding big block of comment/documentation at the beginning of the file.
See: https://github.com/rspec/rspec-core/pull/2683/commits/90af053421d7aac3626f32750a115ee71d48f4ae

Also in `documentation/3.9/rspec-rails/RSpec/Rails/MailerExampleGroup.html` I agree with the change form Yard. The previous documentation we had was if `ActionMailer` was not defined.

---

Next step will be to fix the comment visual issue in Yard, then change `rspec-dev` rake command to deal with `rspec-rails` 4 documentation.

**Comment by benoittgt** [comment]
> is it just the differ's output?

Yes it is :)

Capture d’écran 2020-03-07 à 21 28 23


Thanks for the review.

**Comment by JonRowe** [comment]
If you're happy after diffing it @benoittgt :👍:

**Comment by benoittgt** [comment]
Thanks!

I will turn CI in green for all the PR against `3-9-maintenance`:
- https://github.com/rspec/rspec-core/pull/2683
- https://github.com/rspec/rspec-expectations/pull/1152
- https://github.com/rspec/rspec-mocks/pull/1311
- https://github.com/rspec/rspec-rails/compare/3-9-maintenance...enable-yard-and-bump-doc

Then I will merge and commit the change on master on each project.

**Pull request merged**
